language: node_js
node_js:
  - "11"

install:
  - yarn

matrix:
  include:
    - script:
        - yarn build:all
        - yarn coverage
        - yarn run codecov
      name: "Coverage"
    - script: yarn karma --browsers ChromeWindows10
      name: "Latest Chrome on Windows 10"
    - script: yarn karma --browsers Chrome70Windows7
      name: "Chrome 70 on Windows 7"
    - script: yarn karma --browsers EdgeWindows10
      name: "Latest Edge"
    - script: yarn karma --browsers FirefoxWindows10
      name: "Latest Firefox on Windows 10"
    - script: yarn karma --browsers Firefox64Windows8
      name: "Firefox 64 on Windows 8.1"
    - script: yarn karma --browsers ChomeOSX
      name: "Chrome on OS X"
    - script: yarn karma --browsers FirefoxOSX
      name: "Firefox on OS X"
    - script: yarn karma --browsers Android9
      name: "Chrome Android 9"
    - script: yarn karma --browsers Android5
      name: "Chrome Android 5"
    - script: yarn karma --browsers iOS12
      name: "Safari iOS 12"
  allow_failures:
    - script: yarn karma --browsers Safari12Mojave
      name: "Safari 12 on OS X Mojave"
