[tool.poetry]
name = "tanker-js-sdk"
version = "0.1.0"
description = "Tanker Javascript client"
authors = ["Tanker dev team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
tankerci = { version = ">= 2021.06.3455", source = "gitlab" }

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "0.790"

[[tool.poetry.source]]
name = "gitlab"
url = "https://gitlab.com/api/v4/projects/20917546/packages/pypi/simple"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
