[tool.poetry]
name = "tanker-js-sdk"
version = "0.1.0"
description = "Tanker Javascript client"
authors = ["Tanker dev team <tech@tanker.io>"]

[tool.poetry.dependencies]
python = "^3.7"
ci = "2020.7.2608"

[tool.poetry.dev-dependencies]
flake8 = "^3.7.9"
mypy = "0.740"

[[tool.poetry.source]]
name = "tanker.local"
url = "http://tanker.local:8181"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
